### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Dharani077718** [TDanks2000/StreamAble-app#12]
The problem is the ui scrolling is laggy and the search is not working

**Comment by Dharani077718** [comment]
And while opening some anime like bocchi the rock
The app crashes 
Pls fix this asap

**Comment by TDanks2000** [comment]
after Christmas break will get to it

**Comment by TDanks2000** [comment]
make sure you are on the latest version of the app, as i have not encountered any of the problems you are saying

**Comment by Dharani077718** [comment]
Ok thank you
