### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by Dharani077718** [TDanks2000/StreamAble-app#14]
When i type blue lock nothing appears
![Screenshot_20221227_142833](https://user-images.githubusercontent.com/121377602/209641951-6aba61d6-ba19-468f-b553-d19ebb58a8ef.jpg)

But when I type only blue it appears
![Screenshot_20221227_142847](https://user-images.githubusercontent.com/121377602/209641734-4f8aba08-a6f4-471b-88cf-056161f29e08.jpg)
Same with bocchi the rock

Not everyone can type exact name
    

Pls fix this

**Comment by TDanks2000** [comment]
I'll have a look at this later

**Comment by TDanks2000** [comment]
fixed

**Comment by TDanks2000** [comment]
> It is still the same

yes cause i havent pushed a release

**Comment by Dharani077718** [comment]
Ok bro waiting for it .btw change the video timeline it starts from 30 and ends in 50 

It is supposed to go from 0 to 20 right

**Comment by TDanks2000** [comment]
> 
i cant reproduce this issue when ive tried


> Ok bro waiting for it .btw change the video timeline it starts from 30 and ends in 50
> 
> It is supposed to go from 0 to 20 right
