### ISSUE TITLE
Hello Can u fix it

### ISSUE THREAD

**Issue by nanotechis** [TDanks2000/StreamAble-app#2]
can u make it auto landscape mode when playing a video thankyou

**Comment by TDanks2000** [comment]
it should rotate if you turn off portrait lock on android

**Comment by TDanks2000** [comment]
iill look into making the video player ignore the potrait lock

**Comment by TDanks2000** [comment]
going into player now auto locks to landscape, fixed in next build release

Thank you for taking the time to report the issue
