### ISSUE TITLE
Looking forward to this app

### ISSUE THREAD

**Issue by MrConqueror** [TDanks2000/StreamAble-app#3]
Hoping for more features and improvements. Actually regarding the Player here's what i thought 
![IMG_20221202_180437](https://user-images.githubusercontent.com/102837820/205267936-67fe48e4-312f-4e7b-9a72-34d5b493cae0.jpg)

**Comment by MrConqueror** [comment]
Man you sure have a such a nice app to watch anime, cool UI and Episode List it includes thumbnail and Episode's title. But i have found one problem is that when you chose an episode it takes 3secs before it plays. Not much of an issue though

**Comment by TDanks2000** [comment]
> 



> Man you sure have a such a nice app to watch anime, cool UI and Episode List it includes thumbnail and Episode's title. But i have found one problem is that when you chose an episode it takes 3secs before it plays. Not much of an issue though

this is a problem with the place i get the video links from.
