### ISSUE TITLE
LoL I don't have any issues I just wanna say this app is good 😊😊

### ISSUE THREAD

**Issue by Bootylickerbutalt** [TDanks2000/StreamAble-app#4]
This app is good 😊

**Comment by TDanks2000** [comment]
Thank you really appreciate that, be sure to start the repo thank you :)

**Comment by Bootylickerbutalt** [comment]
> 
I don't know what that is I just spend my day looking for a anime streaming app

**Comment by Bootylickerbutalt** [comment]
Hey bro I was just wondering why are some episodes missing?

**Comment by TDanks2000** [comment]
which anime, which episodes?

**Comment by Bootylickerbutalt** [comment]
This is kinda embarrassing you see Im 15 now but I wanted to watch my
favorite show when I was a kid Doraemon don't ask why I wanted to rewatch
it's movies but I saw some of it doesn't have an episode 😅
