### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by Nieclypes** [TDanks2000/StreamAble-app#5]
This isn't really a issue for me because I know the app is new but when I got to in the settings and click on one of the columns, it does nothing.

**Comment by TDanks2000** [comment]
> This isn't really a issue for me because I know the app is new but when I got to in the settings and click on one of the columns, it does nothing.

Settings aren't added yet there all just placeholders

**Comment by Nieclypes** [comment]
> > This isn't really a issue for me because I know the app is new but when I got to in the settings and click on one of the columns, it does nothing.
> 
> Settings aren't added yet there all just placeholders

oh ok that makes sense sorry
also when will there be anilist and myanimelist support

**Comment by TDanks2000** [comment]
> > > This isn't really a issue for me because I know the app is new but when I got to in the settings and click on one of the columns, it does nothing.
> > 
> > Settings aren't added yet there all just placeholders
> 
> oh ok that makes sense sorry
> also when will there be anilist and myanimelist support

What do you mean?

**Comment by TDanks2000** [comment]
Anilist and mal tracking?

**Comment by Nieclypes** [comment]
> Anilist and mal tracking?

It shows in the planned feature mal and anilist sync

**Comment by TDanks2000** [comment]
> > Anilist and mal tracking?
> 
> It shows in the planned feature mal and anilist sync

I'm working on these right now

**Comment by Nieclypes** [comment]
> > > Anilist and mal tracking?
> > 
> > 
> > It shows in the planned feature mal and anilist sync
> 
> I'm working on these right now

cool cant wait and btw love ui of the app it is responsive and fast

**Comment by TDanks2000** [comment]
> > > > Anilist and mal tracking?
> > > 
> > > 
> > > It shows in the planned feature mal and anilist sync
> > 
> > 
> > I'm working on these right now
> 
> cool cant wait and btw love ui of the app it is responsive and fast

Thank you really appreciate it, dont forget to star the github repo
