### ISSUE TITLE
UI enhancement 

### ISSUE THREAD

**Issue by MrConqueror** [TDanks2000/StreamAble-app#7]
What do you think with these Navigation? 
Phone's Navigation button should always be visible
Separate watchlist and move them to Library instead.
Placing them in Homepage kinda looks like a mess

![Screenshot_2022-12-08-14-07-48-879_com deceptions no](https://user-images.githubusercontent.com/102837820/206371197-6aaea5ef-35b4-4a96-9e6b-6253a7415e1a.jpg)
![Screenshot_2022-12-08-13-59-42-859_com deceptions no](https://user-images.githubusercontent.com/102837820/206369444-13018228-daa1-4212-bc8c-33b67466bbe7.jpg)
![Screenshot_2022-12-08-14-07-48-879_com deceptions no](https://user-images.githubusercontent.com/102837820/206371197-6aaea5ef-35b4-4a96-9e6b-6253a7415e1a.jpg)
![Uploading Screenshot_2022-12-08-14-07-48-879_com.deceptions.no.jpg…]()

**Comment by TDanks2000** [comment]
I'm going to add the button on the nav to goto lists also the phone navigation can easily be accessed by swiping up from the bottom of the phone

**Comment by MrConqueror** [comment]
> I'm going to add the button on the nav to goto lists also the phone navigation can easily be accessed by swiping up from the bottom of the phone

Idk but personally It's quite difficult to navigate like that

**Comment by TDanks2000** [comment]
> > I'm going to add the button on the nav to goto lists also the phone navigation can easily be accessed by swiping up from the bottom of the phone
> 
> Idk but personally It's quite difficult to navigate like that i mean hassle



> > I'm going to add the button on the nav to goto lists also the phone navigation can easily be accessed by swiping up from the bottom of the phone
> 
> Idk but personally It's quite difficult to navigate like that i mean hassle



> > I'm going to add the button on the nav to goto lists also the phone navigation can easily be accessed by swiping up from the bottom of the phone
> 
> Idk but personally It's quite difficult to navigate like that i mean hassle

okay i added lists page.

I did have the navigation always showing before, but I had some problems with it ill have a look again now to show it and then hide it once on the player screen
