### ISSUE TITLE
Settings! 

### ISSUE THREAD

**Issue by meadow5290** [TDanks2000/StreamAble-app#9]
I can't open anything in settings, the only thing I can do is, login/Update.

Please, fix,

Thanks...

**Comment by TDanks2000** [comment]
> I can't open anything in settings, the only thing I can do is, login/Update.
> 
> Please, fix,
> 
> Thanks...

what version are you on?

**Comment by TDanks2000** [comment]
also there is only one setting in the latest version everything else is a placeholder
